- app/Http/Controllers/AdminController.php
- public/css/admin-style.css
- resources/views/admin/users/allusers.blade.php
- resources/views/layouts/admin-app.blade.php
when Admin login, allusers.blade.php will show up first.
If there are users who already registered, it will show in the table.
> I change page name from "users.balde.php" to "allusers.blade.php". 

- app/Http/Controllers/Auth/LoginController.php
- resources/views/admin/users/allusers.blade.php
- resources/views/admin/users/modal/showprofile.blade.php
The admin won't show up in the users table, because it isn't needed. And I'm not sure about LoginController already changed or not. so I changed it. now I can jumped in to the top page for admin if the admin login.
> I changed allusers.blade.php

- app/Models/Event.php
- app/Models/Level.php
- app/Models/Meeting.php
- app/Models/Participant.php
- app/Models/User.php
- composer.json
- composer.lock
- database/migrations/2023_06_05_144810_modify_date_in_categories.php
- database/migrations/2023_06_05_150334_modify_table_events.php
- database/seeders/CategorySeeder.php
- database/seeders/LevelSeeder.php
1. Migration - add(modify categories and events)
2. Model - fix (rename function and delete relation)
3. Seeder - fix (value change)
4. new library "doctrine/dbal" (for migration files)
> Migration fix

- resources/scss/event.scss
- routes/web.php
- webpack.mix.js
changed routes/web for event page, since the old one was only shown for log in users
> There was a bug on routes/web.  Moved userevent group.

- routes/web.php
I accidentally PR old code.  Please change it to the newest name.  Thank you.
> I pushed old code, so I would like to change the name for the newest.

- app/Http/Controllers/Auth/RegisterController.php
- app/Providers/RouteServiceProvider.php
- resources/scss/privacy_terms.scss
- resources/views/privacy.blade.php
- resources/views/terms.blade.php
1. add a function registered to check if user is already a participant
2. change redirect route after login or registered
3. small fix 2 blade files, privacy and terms.
> fix admin controller

- app/Http/Controllers/HomeController.php
- app/Models/User.php
- resources/scss/modal.scss
- resources/scss/users-style.scss
- resources/views/users/reserved/join_users.blade.php
- resources/views/users/reserved/show_details.blade.php
- resources/views/users/top.blade.php
- routes/web.php
The following files have been modified.
1. HomeController
To show "reserved.show_details"page and "reserved.join_users"page.
2. User.php
Add "use App\Models\Participant".
3. modal.scss
Fix to minimum height.
4. top.blade.php
Add "/" . With this addition, the category image now appears.
5. join_users.blade.php
New file.
6. show_details.blade.php
New file.
7. web.php
Add line72 to show "join_users.blade.php"
> Create related Reserved page files.

- app/Http/Controllers/ContactController.php
- resources/js/contact-us.js
- resources/scss/contact-us.scss
- resources/views/contact-us.blade.php
- webpack.mix.js
If it is the user, there are two different things from the guest. (The form for guest is the same as before)
1. To add an option, 'review', in the subtitle's input options. 
2. If the user chooses 'review', a new input for 'rating the app' appeared below the subtitle input.
> I changed the inputs of UI for the contact-us form

- app/Http/Controllers/MeetingController.php
- resources/scss/users-style.scss
- resources/views/users/research/create_meeting.blade.php
- resources/views/users/reserved/show_details.blade.php
- resources/views/users/top.blade.php
- routes/web.php
＊Related to ”create meeting" page.
1. Meeting Controller
2. scss
3. create_meeting.blade.php(new file)
4. top.blade.php
TIME TABLE is temporary and not yet completed. TIME TABLE part will be created later.
5. web.php
＊Related to "select box"
6. show.details.blade.php
Add only UI.
> Create "create meeting"page and select box.

- app/Http/Controllers/ContactController.php
- database/migrations/2023_06_20_205517_add_rating_to_contacts_table.php
- database/seeders/SubtitleSeeder.php
- resources/views/contact-us.blade.php
１．Fix the store function in ContactController
２.   Let 'rating' data send to the database only if the user choose 'Review' in the subtitle dropdown.
> Contact-us function with JavaScript

- app/Http/Controllers/Admin/MeetingsController.php
- app/Models/Meeting.php
- database/migrations/2023_06_20_210946_modify_start_at_in_meetings.php
- resources/views/admin/chatrooms/components/meetingList.blade.php
- resources/views/admin/chatrooms/meetings/edit.blade.php
- resources/views/admin/chatrooms/meetings/modals/detail.blade.php
1. fix database. Modify start_at column in meetings table (type change 'int' -> 'time')
2. fix model, contorller and blade files related with the db changing
> fix database. meetings table

- app/Http/Controllers/HomeController.php
- resources/scss/modal.scss
- resources/scss/users-style.scss
- resources/views/users/research/modals/reservation.blade.php
- resources/views/users/research/show.blade.php
- resources/views/users/reserved/join_users.blade.php
- resources/views/users/reserved/show_details.blade.php
- resources/views/users/top.blade.php
- routes/web.php
＊Create research page
HomeController.php
web.php
users/top.blade.php
users/research/show.blade.php
users/research/modals/reservation.blade.php
＊Fix UI
modal.scss
style-users.scss
users/reserved/join_users.blade.php
＊Add @if
users/reserved/show_details.blade.php
　→Added a check for the existence of the participant. (Kenneth's comment on June 22 in Slack.)
> Create related "research page", fix UI and add @if.

- app/Http/Controllers/EventController.php
- resources/views/users/events/event_detail.blade.php
- resources/views/users/events/index.blade.php
- resources/views/users/events/modals/join_event.blade.php
- routes/web.php
Also removed show method for guest.
> Created destroyAuthParticipant method.

- resources/views/users/events/index.blade.php
UI must be fixed a bit more, but it works properly now.
> Fixed carousel part for users.events.index.

- app/Http/Controllers/WelcomeController.php
- resources/scss/welcome.scss
- resources/views/welcome.blade.php
- routes/web.php
Retreive the username and level of the user who wrote review, and the rating and content of the review.
> Display the review of the app inserted in the contact-us form.

- resources/scss/event.scss
- resources/views/users/events/index.blade.php
also trimed not necessary "!important" in scss
> Fixed color and place for the carousel icon

- database/migrations/2023_06_20_210946_modify_start_at_in_meetings.php
> Fix migration file type error

- app/Http/Controllers/Auth/RegisterController.php
- app/Models/User.php
small fix because of adding relateion User and Participant in previous PR
> fix model and controller

- app/Http/Controllers/MeetingController.php
- resources/views/users/profile/edit.blade.php
- resources/views/users/research/modals/reservation.blade.php
- resources/views/users/research/show.blade.php
- routes/web.php
＊Fix UI
resources/views/users/profile/edit.blade.php　　(Added because I forgot to do so)
resources/views/users/research/show.blade.php.   (Change icon because the previous icon was confusing)
＊Create function
I added "attach()" method.
routes/web.php
app/Http/Controllers/MeetingController.php
resources/views/users/research/modals/reservation.blade.php
> Fix UI and create function.

- resources/scss/admin-style.scss
- resources/views/admin/users/allusers.blade.php
- resources/views/admin/users/modal/showprofile.blade.php
Also I fixed scss for avatar both in users table and in modal which shows profile detail.
> I added the path for profile image.

- resources/scss/style.scss
- resources/views/layouts/app.blade.php
> Adjusted footer design and added SNS links.

- resources/views/admin/events/create.blade.php
- resources/views/admin/events/edit.blade.php
- resources/views/admin/events/index.blade.php
- resources/views/admin/events/participants.blade.php
- resources/views/admin/inbox/index.blade.php
- resources/views/admin/users/allusers.blade.php
- resources/views/layouts/admin-app.blade.php
I created @yield('highlight_text') and @yield('subtitle') in admin-app.blade.php
I used it as the title in each admin page.
> I fixed the title for each admin page.

- resources/views/users/events/modals/join_event.blade.php
- resources/views/users/meetings/modals/calendar.blade.php
- resources/views/users/research/modals/reservation.blade.php
- resources/views/users/reserved/modals/cancel_meeting.blade.php
- resources/views/users/reserved/modals/delete.blade.php
- resources/views/users/reserved/modals/join.blade.php
> Fix Modals UI.

- resources/views/admin/inbox/index.blade.php
I added the function for search messages by javascript
> Search for messages in admin page.

- app/Http/Controllers/Admin/EventsController.php
- resources/views/admin/events/participants.blade.php
I added the pagination for participant list in admin page.
> I added the pagination for participant list in admin page.

- resources/views/admin/events/index.blade.php
I created the function to search for events by using javascript.
> Search for events in admin page.

- resources/scss/admin_chatroom.scss
- resources/views/admin/chatrooms/categories/add.blade.php
- resources/views/admin/chatrooms/categories/edit.blade.php
- resources/views/admin/chatrooms/categories/index.blade.php
- resources/views/admin/chatrooms/categories/modals/action.blade.php
- resources/views/admin/chatrooms/categories/show.blade.php
- resources/views/admin/chatrooms/components/bar.blade.php
- resources/views/admin/chatrooms/components/meetingList.blade.php
- resources/views/admin/chatrooms/meetings/edit.blade.php
- resources/views/admin/chatrooms/meetings/index.blade.php
- resources/views/admin/chatrooms/meetings/modals/action.blade.php
- resources/views/admin/chatrooms/rooms/index.blade.php
- resources/views/admin/chatrooms/rooms/modals/action.blade.php
- resources/views/admin/chatrooms/rooms/show.blade.php
1. Add @section subtitle and hilight_text
2. Fix modals UI
3. Fix pagination UI
> Fix UI. Admin chatroom pages

- resources/scss/users-style.scss
- resources/views/users/profile/show.blade.php
> Fixed profile UI.

- resources/views/admin/events/participants.blade.php
I created the function to search for participants by using javascript.
> Search for participants in admin page.

- app/Models/Meeting.php
- resources/views/users/research/modals/reservation.blade.php
1. new function and const in Meeting Model
2. add condition in blade
> put limit on users joining a meeting.

- app/Http/Controllers/HomeController.php
- resources/views/users/reserved/modals/cancel_meeting.blade.php
- resources/views/users/reserved/modals/delete.blade.php
- resources/views/users/reserved/modals/join.blade.php
- resources/views/users/reserved/show.blade.php
- resources/views/users/reserved/show_details.blade.php
Create join button which will appear in time.
> Create join button.

- app/Http/Controllers/Admin/EventsController.php
- database/migrations/2023_07_06_205606_add_participants_limit_to_events.php
- resources/views/admin/events/create.blade.php
- resources/views/admin/events/edit.blade.php
- resources/views/admin/events/index.blade.php
I added one field to the Create Event and Edit Event forms to enter the maximum number of participants.
Accordingly I fixed the condition for the event status @elseif.
> I added the column that an event has limit of participants.

- app/Http/Controllers/EventController.php
- resources/views/users/events/index.blade.php
if the event date in the database passed, it should be hidden.
> I fixed Event page.

- app/Http/Controllers/EventController.php
- resources/views/users/events/index.blade.php
If participants of the event reached the limit, the event should be hidden.
> I added the condition of showing events.

- resources/views/users/events/index.blade.php
If the event has not yet reached the maximum number of participants, it will show the remaining number of available applications.
> Display the number of remaining available applications.

- resources/scss/users-style.scss
- resources/views/users/pagination.blade.php
- resources/views/users/profile/show.blade.php
- resources/views/users/research/show.blade.php
- resources/views/users/reserved/show.blade.php
- resources/views/users/reserved/show_details.blade.php
- resources/views/users/top.blade.php
> Create pagination and fix UI.

- app/Http/Controllers/WelcomeController.php
- package.json
- resources/js/Welcome.js
- resources/js/app.js
- resources/js/components/Pagination.js
- resources/js/components/Reviews.js
- resources/js/index.js
- resources/scss/welcome.scss
- resources/views/contact-us.blade.php
- resources/views/welcome.blade.php
- webpack.mix.js
The property flow; 
WelcomeController->welcome.blade.php->index.js->Welcome.js->Pagination.js / Reviews.js
I ran this command; npm install react-paginate --save
> create review-pagination using React

- resources/scss/admin-style.scss
- resources/scss/form.scss
- resources/views/admin/chatrooms/categories/add.blade.php
- resources/views/admin/chatrooms/categories/edit.blade.php
- resources/views/layouts/admin-app.blade.php
1. adjust css
2. add script to change the appearance model color
> fix ui and add script in blade

- resources/scss/users-style.scss
- resources/views/users/profile/show.blade.php
- resources/views/users/research/show.blade.php
- resources/views/users/reserved/show_details.blade.php
- resources/views/users/top.blade.php
Fix error and UI of user's pages.
> Fix UI of user's pages.

- app/Http/Controllers/Admin/EventsController.php
I removed ':00' because I got the error.
> I found the part I should fix.

- app/Http/Controllers/Admin/MeetingsController.php
- app/Http/Controllers/Admin/RoomsController.php
- app/Http/Controllers/HomeController.php
- app/Http/Controllers/MeetingController.php
- app/Http/Controllers/ZoomController.php
- app/Models/Meeting.php
- app/Models/Room.php
- app/Models/Zoom_account.php
- app/Models/Zoom_meeting.php
- database/migrations/2023_07_07_115012_create_zoom_meetings_table.php
- database/migrations/2023_07_07_115030_create_zoom_accounts_table.php
- resources/scss/admin_chatroom.scss
- resources/views/admin/chatrooms/meetings/index.blade.php
- resources/views/admin/chatrooms/meetings/modals/action.blade.php
- resources/views/admin/chatrooms/meetings/modals/detail.blade.php
- resources/views/admin/chatrooms/rooms/index.blade.php
- resources/views/admin/chatrooms/rooms/modals/zoom.blade.php
- resources/views/admin/chatrooms/rooms/show.blade.php
- resources/views/users/meetings/calendar.blade.php
- routes/web.php
1. Create 2 migrateion
2. Create 2 models and define relation
3. Create ZoomController and define functions
4. Fix functions about CRUD meetings
5. Fix UI for zoom api
6. add routes
7. add .env variables
1) ZOOM_CLIENT_ID
2) ZOOM_CLIENT_SECRET
3) APP_URL=http://localhost:8000
> Add Zoom Api Controller and fix ui

- app/Http/Controllers/Admin/MeetingsController.php
- app/Http/Controllers/Admin/RoomsController.php
- resources/views/privacy.blade.php
- resources/views/users/meetings/calendar.blade.php
- resources/views/users/reserved/modals/join.blade.php
1. privacy - download button
2. users - description
3. admin chatrooms table
> fix ui in some pages

- app/Http/Controllers/ProfileController.php
- resources/views/users/reserved/show_details.blade.php
> Changed destroyProfile method.

- app/Http/Controllers/Admin/UsersController.php
If the user that the admin wants to deactivate had sent review, the review will be deleted.
> I fixed function deactivate for admin.

- app/Http/Controllers/MeetingController.php
- resources/scss/style.scss
- resources/scss/users-style.scss
- resources/views/users/events/modals/join_event.blade.php
- resources/views/users/meetings/modals/calendar.blade.php
- resources/views/users/research/modals/create_meeting.blade.php
- resources/views/users/research/modals/reservation.blade.php
- resources/views/users/reserved/modals/cancel_event.blade.php
- resources/views/users/reserved/modals/cancel_meeting.blade.php
- resources/views/users/reserved/show.blade.php
- resources/views/users/reserved/show_details.blade.php
Fix UI
Add error session
Show "category" of create.meeting modal
> Fix UI and add error-session

- app/Http/Controllers/FollowController.php
- app/Models/User.php
- database/migrations/2023_07_15_090740_create_follows_table.php
- resources/scss/follow.scss
- resources/scss/users-style.scss
- resources/views/users/profile/edit.blade.php
- resources/views/users/profile/follower.blade.php
- resources/views/users/profile/following.blade.php
- resources/views/users/profile/header.blade.php
- resources/views/users/profile/show.blade.php
- resources/views/users/reserved/join_users.blade.php
- routes/web.php
- webpack.mix.js
<UI>
1. Delete the edit button in profile/show.blade.php because we can go to edit in the profile page 
2. Direct to the profile page for the user in the list for the meeting instead of showing the modal in join_users.blade.php
3. edit the header.blade.php
4. edit the followers.blade.php
5. edit the following.blade.php
6. Change the destination when the user click cancel button in profile/edit page
7. Adjust UI in follow.scss
8. Add follow.scss route in webpack.mix.js
9. Adjust profile/show page UI in user-style.scss
<Function>
1. php artisan make:migration create_follows_table --create=follows
2. edit the data in the database
3. php artisan make:controller FollowController
4. Create the relation methods in User model
5. add functions in the controller
6. Create routes in web.php
> create follow functions and UI

- app/Http/Controllers/Admin/MeetingsController.php
- app/Models/Category.php
- app/Models/Room.php
- resources/scss/admin_chatroom.scss
- resources/views/admin/chatrooms/meetings/result.blade.php
- routes/web.php
1. add sort button in admin all meetings page.
2. create result page.
3. fix models to change order
4. fix ui
> add result page in admin meetings

- resources/scss/users-style.scss
- resources/views/users/meetings/modals/calendar.blade.php
- resources/views/users/modals/error_meeting.blade.php
- resources/views/users/profile/modal/delete.blade.php
- resources/views/users/profile/show.blade.php
- resources/views/users/research/modals/create_meeting.blade.php
- resources/views/users/research/show.blade.php
- resources/views/users/top.blade.php
Created "session-error" page 
Changed the position of script
Fix UI
> Created "session-error" page and changed the position of script.

- app/Http/Controllers/Admin/MeetingsController.php
- app/Http/Controllers/HomeController.php
- app/Models/Category.php
- app/Models/Meeting.php
- app/Models/Room.php
- resources/views/users/meetings/calendar.blade.php
- resources/views/users/research/modals/create_meeting.blade.php
- resources/views/users/research/modals/reservation.blade.php
- resources/views/users/reserved/modals/join.blade.php
- resources/views/users/reserved/show_details.blade.php
unified rules of times about meeting
1. display meeting info time
2. allow for creation of new meeting time
3. display zoom join button time
> Unified rules for viewing meetings

- resources/views/users/reserved/join_event_users.blade.php
- resources/views/users/reserved/join_users.blade.php
- resources/views/users/reserved/show_details.blade.php
*Auth::user() can go to own profile page.
> Fixed users/reserved/join_event_users UI and add new route.

- resources/views/users/research/modals/reservation.blade.php
> fix condition

- resources/scss/welcome.scss
- resources/views/users/events/index.blade.php
- resources/views/welcome.blade.php
> Add video and fix UI.

- app/Http/Controllers/HomeController.php
- app/Http/Controllers/MeetingController.php
- resources/views/users/meetings/calendar.blade.php
- resources/views/users/meetings/modals/calendar-action.blade.php
- resources/views/users/meetings/result.blade.php
- resources/views/users/research/modals/create_meeting.blade.php
- resources/views/users/research/show.blade.php
- resources/views/users/top.blade.php
1. Remove unused statements in Controllers
2. Fix UI
3. move the script declaration
> fix meeting controller and UI

- app/Http/Controllers/ContactController.php
- app/Http/Middleware/AdminMiddleware.php
- resources/views/contact-us.blade.php
fix validation for contacts
fix admin middleware redirect URL
> fix validation and admin middleware

- app/Http/Controllers/Admin/EventsController.php
- resources/views/admin/events/create.blade.php
It missed validation for image and level_id in EventsController which is for admin page, so I fixed.
> I added validation for EventsController.

- app/Http/Controllers/ProfileController.php
- resources/views/users/events/event_detail.blade.php
- resources/views/users/events/modals/join_event.blade.php
- resources/views/users/reserved/modals/cancel_event.blade.php
- resources/views/users/reserved/modals/cancel_meeting.blade.php
- resources/views/users/reserved/modals/delete.blade.php
- resources/views/users/reserved/show_details.blade.php
- routes/web.php
*change modal button color
*removed confirm join modal
*organized UI from table to div
> Changed UI and deleted unnecessary route and code.

- app/Http/Controllers/MeetingController.php
- app/Http/Controllers/ProfileController.php
- routes/web.php
Fix validation and delete codes that were not in use.
> FIx validation.

- app/Http/Controllers/Admin/EventsController.php
- resources/views/admin/events/create.blade.php
When admin create new events, the error showed up for levels.
I changed the validation for that.
> I fixed the error.

- resources/views/users/profile/modal/follower.blade.php
I fixed the route name of the avatar icon in the follower modal
> I fixed the route of avatar

- app/Http/Controllers/Admin/EventsController.php
- app/Http/Controllers/ProfileController.php
- config/filesystems.php
- resources/views/users/events/index.blade.php
This doesn't have to be merged.  Just would like to be checked.  Thank you:-)
> change image

- app/Http/Controllers/ZoomController.php
> fix type error
